// Schema (DDL) exports
export {
  v2PostgresDdlAdapterConfigSchema,
  PostgresTableSchemaRepository,
  createSchemaRuleContext,
  PostgresSchemaIntrospector,
  ColumnExistsRule,
  ColumnUniqueConstraintRule,
  createFieldSchemaRules,
  FieldMetaRule,
  FieldSchemaRulesVisitor,
  FkColumnRule,
  ForeignKeyRule,
  GeneratedColumnRule,
  IndexRule,
  JunctionTableExistsRule,
  JunctionTableForeignKeyRule,
  JunctionTableIndexRule,
  LinkSymmetricFieldRule,
  LinkValueColumnRule,
  NotNullConstraintRule,
  OrderColumnRule,
  ReferenceRule,
  UniqueIndexRule,
  createSystemTableRules,
  SYSTEM_RULE_FIELD_ID,
  SYSTEM_RULE_FIELD_NAME,
  addGeneratedColumnStatement,
  buildTableIdentifier,
  compressSql,
  createForeignKeyConstraintStatement,
  createIndexStatement,
  createUniqueIndexStatement,
  dropColumnStatement,
  dropConstraintStatement,
  dropIndexStatement,
  dropTableStatement,
  SchemaRuleResolver,
  schemaRuleResolver,
  calculateRuleDepths,
  createSchemaRulePlanner,
  getSchemaRulePlanningStageDescription,
  SchemaRulePlanner,
  createSchemaChecker,
  getRuleDescription,
  SchemaChecker,
  createSchemaRepairer,
  errorResult,
  pendingResult,
  SchemaRepairer,
  FieldValueChangeCollectorVisitor,
  TableAddFieldCollectorVisitor,
  TableSchemaUpdateVisitor,
  PostgresTableSchemaFieldCreateVisitor,
} from './schema';
export type {
  IV2PostgresDdlAdapterConfig,
  ColumnInfo,
  ConstraintInfo,
  ForeignKeyInfo,
  IndexInfo,
  SchemaIntrospector,
  SchemaRuleContext,
  ISchemaRule,
  SchemaRuleManualRepairOptions,
  SchemaRuleManualRepairValues,
  SchemaRuleRepairHint,
  SchemaRuleValidationResult,
  TableSchemaStatementBuilder,
  FieldSchemaRulesContext,
  JunctionTableConfig,
  ReferenceEntry,
  TableIdentifier,
  ISchemaRuleResolver,
  RuleResolutionResult,
  SchemaRuleFieldPlan,
  SchemaRulePlanEntry,
  SchemaRulePlanError,
  SchemaRulePlannerParams,
  SchemaRulePlanningStage,
  SchemaRuleTarget,
  SchemaCheckResult,
  SchemaCheckerParams,
  SchemaCheckStatus,
  SchemaRepairDetails,
  SchemaRepairOutcome,
  SchemaRepairOptions,
  SchemaRepairResult,
  SchemaRepairStatus,
  SchemaRepairerParams,
  ICreateTableBuilderRef,
} from './schema';
export {
  baseRecordColumnNames,
  convertNameToValidCharacter,
  joinDbTableName,
  ensureUniqueDbFieldName,
} from './schema/naming';

// Record (DML) exports
export {
  FieldOutputColumnVisitor,
  TableRecordQueryBuilderManager,
  COMPUTED_TABLE_ALIAS,
  ComputedTableRecordQueryBuilder,
  ComputedFieldSelectExpressionVisitor,
  StoredFieldSelectVisitor,
  StoredTableRecordQueryBuilder,
  RecordInsertBuilder,
  RecordUpdateBuilder,
  defaultFieldBackfillConfig,
  ComputedFieldBackfillService,
  ComputedFieldCascadeAfterSchemaUpdate,
  ComputedUpdateDrainService,
  ComputedFieldUpdater,
  defaultComputedUpdateLockConfig,
  COMPUTED_UPDATE_LOCK_UNAVAILABLE_CODE,
  buildComputedUpdateLockPlan,
  buildAdvisoryLockStatement,
  buildAdvisoryLockQuery,
  buildTryAdvisoryLockQuery,
  isComputedUpdateLockUnavailable,
  allTargetRecordsReasonValues,
  isAllTargetRecordsReason,
  ComputedUpdatePlanner,
  computedFieldTypes,
  isComputedFieldType,
  splitSeedGroupsForPlan,
  createComputedUpdateRun,
  toRunLogContext,
  toRunSpanAttributes,
  ExternalComputedRefreshService,
  RunComputedTaskByIdCommand,
  RunComputedTaskByIdHandler,
  UserRenamePropagationService,
  FieldDependencyGraph,
  UpdateFromSelectBuilder,
  isPersistedAsGeneratedColumn,
  dedupeClaimRowsByScope,
  ComputedUpdateOutbox,
  mergeBeforeImageRecordDtos,
  serializeComputedUpdatePlan,
  computePlanHash,
  buildOutboxTaskInput,
  mergeComputedRealtimeOrchestration,
  deserializeComputedUpdatePlan,
  serializeSeedPayload,
  deserializeSeedPayload,
  computeSeedHash,
  buildSeedTaskInput,
  isSeedPayload,
  mergeSeedPayloads,
  serializeFieldBackfillPayload,
  deserializeFieldBackfillPayload,
  computeFieldBackfillHash,
  buildFieldBackfillTaskInput,
  isFieldBackfillPayload,
  defaultComputedUpdateOutboxConfig,
  normalizeComputedUpdateOutboxConfig,
  isFieldBackfillOutboxItem,
  isSeedOutboxItem,
  ComputedUpdatePauseRegistry,
  buildComputedTaskNotPausedCondition,
  COMPUTED_UPDATE_PAUSE_SCOPE_TABLE,
  computedUpdatePauseScopeTypes,
  AsyncWithRetryStrategy,
  defaultHybridWithOutboxStrategyConfig,
  productionHybridWithOutboxStrategyConfig,
  lowLatencyHybridWithOutboxStrategyConfig,
  HybridWithOutboxStrategy,
  SyncInTransactionStrategy,
  buildBatchUpdateTrigger,
  splitComputedTaskForSeedRecordLimit,
  splitSeedTaskForSeedRecordLimit,
  ComputedUpdateWorker,
  defaultPollingConfig,
  hybridPollingConfig,
  externalPollingConfig,
  ComputedUpdatePollingService,
  startComputedUpdatePollingIfEnabled,
  PostgresTableRecordQueryRepository,
  PostgresTableRecordRepository,
  PostgresRecordMutationSnapshotCaptureService,
  PostgresRecordOrderCalculator,
  PostgresAttachmentLookupService,
  parseThumbnailPath,
  PostgresUserLookupService,
  OffsetStreamPaginationStrategy,
  CursorStreamPaginationStrategy,
  FieldDatabaseValueVisitor,
  FieldSqlLiteralVisitor,
  FieldInsertValueVisitor,
  LinkChangeCollectorVisitor,
  createEmptyCollectedLinkChanges,
  mergeCollectedLinkChange,
  LinkExclusivityConstraintCollector,
  TableRecordConditionWhereVisitor,
  CellValueMutateVisitor,
  FieldDeleteValueVisitor,
} from './record';
export type {
  IQueryBuilderDeps,
  ITableRecordQueryBuilder,
  QB,
  DynamicDB,
  SystemColumn,
  OrderByColumn,
  FieldOutputColumn,
  QueryMode,
  IQueryBuilderManagerOptions,
  IDirtyFilterConfig,
  IComputedQueryBuilderOptions,
  LinkOrderBy,
  LateralColumnType,
  ILateralContext,
  ComputedFieldSelectExpressionVisitorOptions,
  IStoredQueryBuilderOptions,
  CompiledSqlStatement,
  RecordInsertSqlResult,
  RecordInsertDataResult,
  RecordInsertBuilderContext,
  LinkedRecordLockInfo,
  InsertExclusivityConstraint,
  UserFieldColumn,
  RecordUpdateSqlResult,
  RecordUpdateBuilderContext,
  CascadeInput,
  FieldChangeData,
  RecordChangeData,
  StepChangeData,
  ComputedUpdateResult,
  DirtyRecordStats,
  DirtyPropagationStats,
  ExecutePreparedStepsResult,
  PreparedDirtyState,
  ComputedUpdateLockConfig,
  ComputedUpdateLockSummary,
  ComputedUpdateLockRecord,
  ComputedUpdateLockTable,
  ComputedUpdateLockBatch,
  ComputedUpdateLockStatement,
  ComputedUpdateLockPlan,
  UpdateContext,
  ComputedSeedGroup,
  ComputedBeforeImageRecord,
  ComputedBeforeImageRequirements,
  PlanStageContext,
  UpdateImpactHint,
  UpdateStep,
  SameTableBatch,
  DirtyPropagationMode,
  AllTargetRecordsReason,
  ComputedUpdateCyclePolicy,
  ConditionalFilterCondition,
  ComputedDependencyEdge,
  ComputedUpdateCycleInfo,
  ComputedUpdatePlan,
  ComputedUpdateRunPhase,
  ComputedUpdateRunContext,
  IRunComputedTaskByIdCommandInput,
  RunComputedTaskByIdResult,
  FieldDependencyEdge,
  LinkRelationship,
  FieldMeta,
  FieldDependencyGraphData,
  CrossBaseFieldMeta,
  FieldDependencyGraphLoadOptions,
  UpdateRecordFilter,
  DirtyFilterConfig,
  UpdateFromSelectParams,
  UpdateWithReturningResult,
  UpdatedRecordRow,
  OutboxRow,
  ComputedUpdateStepDto,
  ComputedDependencyEdgeDto,
  ComputedUpdateSeedGroupDto,
  ComputedBeforeImageRecordDto,
  ComputedRealtimeOrchestrationDto,
  ComputedUpdateOutboxPayload,
  ComputedUpdateRunMeta,
  ComputedUpdateOutboxTaskInput,
  ComputedUpdateOutboxItem,
  SeedImpactHintDto,
  ComputedUpdateSeedPayload,
  ComputedUpdateSeedTaskInput,
  DeserializedSeedTask,
  OutboxTaskType,
  FieldBackfillOutboxPayload,
  FieldBackfillOutboxTaskInput,
  ComputedUpdateOutboxConfig,
  ClaimBatchParams,
  ClaimByIdParams,
  RenewLeaseParams,
  ReleaseForRetryParams,
  FieldBackfillOutboxItem,
  SeedOutboxItem,
  AnyOutboxItem,
  IComputedUpdateOutbox,
  ComputedUpdatePauseScopeType,
  ComputedUpdatePauseScope,
  PauseComputedUpdateScopeParams,
  ResumeComputedUpdateScopeParams,
  ListComputedUpdatePauseScopesParams,
  IComputedUpdatePauseRegistry,
  UpdateStrategyMode,
  IUpdateStrategy,
  DispatchMode,
  HybridWithOutboxStrategyConfig,
  LinkChangeType,
  LinkRelationshipType,
  LinkChange,
  UpdateTrigger,
  BatchUpdateTrigger,
  ComputedUpdateWorkerParams,
  ComputedUpdateWorkerRunTaskByIdParams,
  ComputedUpdatePollingConfig,
  RecordMutationSnapshotTraceContext,
  IPostgresRecordMutationSnapshotCaptureSession,
  IPostgresRecordMutationSnapshotCaptureService,
  FieldInsertResult,
  QueryExecutor,
  LinkChangeCollectorContext,
  LinkChangeCollectorResult,
  CollectedLinkChanges,
  LinkExclusivityConstraint,
  LinkExclusivityCollectorContext,
  LinkExclusivityCollectorResult,
  RecordConditionWhere,
  TableRecordConditionWhereVisitorOptions,
  MutationStatements,
  CellValueMutateContext,
  FieldDeleteResult,
  OutgoingLinkDeleteOp,
} from './record';

// DI exports (main API)
export {
  createTypeValidationStrategy,
  registerV2TableRepositoryPostgresAdapter,
  registerV2RecordRepositoryPostgresAdapter,
  registerV2PostgresDdlAdapter,
  v2PostgresDdlTokens,
  v2RecordRepositoryPostgresTokens,
} from './di';
export type { IV2TableRepositoryPostgresConfig, IV2RecordRepositoryPostgresConfig } from './di';

// Shared utilities
export {
  getPostgresTransaction,
  resolvePostgresDbOrTx,
  executeCompiledQueries,
  executeTableSchemaStatements,
} from './shared/db';
export {
  describeError,
  PG_UNIQUE_VIOLATION,
  PG_NOT_NULL_VIOLATION,
  isLinkUniqueViolation,
  isUniqueViolation,
  isNotNullViolation,
  extractNotNullColumn,
  extractUniqueColumn,
  wrapDatabaseError,
} from './shared/errors';
export type { DatabaseOperation, WrapDatabaseErrorContext } from './shared/errors';
export { installUndoCaptureGlobals } from './shared/installUndoCaptureGlobals';
export {
  splitSchemaQualifiedTableName,
  toQualifiedIdentifierLiteral,
} from './shared/sqlIdentifiers';
export type { QualifiedIdentifierLiteral } from './shared/sqlIdentifiers';
export {
  invalidateUndoCaptureTableCache,
  ensureUndoCaptureInfrastructure,
  setUndoCaptureBatchId,
  getUndoCaptureBatchId,
  restoreUndoCaptureBatchId,
  clearUndoCaptureBatchId,
  loadAndClearUndoLogRows,
} from './shared/undoCapture';
export type { UndoLogRow, UndoCaptureInfrastructureStatus } from './shared/undoCapture';

// Meta validation
export {
  MetaChecker,
  checkTableMeta,
  checkTableMetaWithTables,
  createMetaValidationContext,
  createMetaValidationContextFromTables,
  createIssue,
  referenceError,
  schemaError,
  warningIssue,
  infoIssue,
  referenceSuccess,
  schemaSuccess,
  MetaValidationVisitor,
} from './meta';
export type {
  MetaCheckerOptions,
  IMetaValidationContext,
  MetaValidationCategory,
  MetaValidationSeverity,
  MetaValidationIssue,
  MetaValidationIssueDetails,
  MetaValidationResult,
} from './meta';

// Utils (PG capability detection)
export { assertTypeValidationPolyfill, hasPgInputIsValid } from './utils/detectPgCapability';
