export { v2PostgresDdlAdapterConfigSchema } from './config';
export type { IV2PostgresDdlAdapterConfig } from './config';
export { registerV2PostgresDdlAdapter } from './di/register';
export { v2PostgresDdlTokens } from './di/tokens';
export { PostgresTableSchemaRepository } from './repositories/PostgresTableSchemaRepository';
export {
  createSchemaRuleContext,
  PostgresSchemaIntrospector,
  ColumnExistsRule,
  ColumnUniqueConstraintRule,
  createFieldSchemaRules,
  FieldMetaRule,
  FieldSchemaRulesVisitor,
  FkColumnRule,
  ForeignKeyRule,
  GeneratedColumnRule,
  IndexRule,
  JunctionTableExistsRule,
  JunctionTableForeignKeyRule,
  JunctionTableIndexRule,
  LinkSymmetricFieldRule,
  LinkValueColumnRule,
  NotNullConstraintRule,
  OrderColumnRule,
  ReferenceRule,
  UniqueIndexRule,
  createSystemTableRules,
  SYSTEM_RULE_FIELD_ID,
  SYSTEM_RULE_FIELD_NAME,
  addGeneratedColumnStatement,
  buildTableIdentifier,
  compressSql,
  createForeignKeyConstraintStatement,
  createIndexStatement,
  createUniqueIndexStatement,
  dropColumnStatement,
  dropConstraintStatement,
  dropIndexStatement,
  dropTableStatement,
  SchemaRuleResolver,
  schemaRuleResolver,
  calculateRuleDepths,
  createSchemaRulePlanner,
  getSchemaRulePlanningStageDescription,
  SchemaRulePlanner,
  createSchemaChecker,
  getRuleDescription,
  SchemaChecker,
  createSchemaRepairer,
  errorResult,
  pendingResult,
  SchemaRepairer,
} from './rules';
export type {
  ColumnInfo,
  ConstraintInfo,
  ForeignKeyInfo,
  IndexInfo,
  SchemaIntrospector,
  SchemaRuleContext,
  ISchemaRule,
  SchemaRuleManualRepairOptions,
  SchemaRuleManualRepairValues,
  SchemaRuleRepairHint,
  SchemaRuleValidationResult,
  TableSchemaStatementBuilder,
  FieldSchemaRulesContext,
  JunctionTableConfig,
  ReferenceEntry,
  TableIdentifier,
  ISchemaRuleResolver,
  RuleResolutionResult,
  SchemaRuleFieldPlan,
  SchemaRulePlanEntry,
  SchemaRulePlanError,
  SchemaRulePlannerParams,
  SchemaRulePlanningStage,
  SchemaRuleTarget,
  SchemaCheckResult,
  SchemaCheckerParams,
  SchemaCheckStatus,
  SchemaRepairDetails,
  SchemaRepairOutcome,
  SchemaRepairOptions,
  SchemaRepairResult,
  SchemaRepairStatus,
  SchemaRepairerParams,
} from './rules';
export { FieldValueChangeCollectorVisitor } from './visitors/FieldValueChangeCollectorVisitor';
export { TableAddFieldCollectorVisitor } from './visitors/TableAddFieldCollectorVisitor';
export { TableSchemaUpdateVisitor } from './visitors/TableSchemaUpdateVisitor';
// Re-export visitor types except TableSchemaStatementBuilder (already exported from rules)
export type { ICreateTableBuilderRef } from './visitors/PostgresTableSchemaFieldCreateVisitor';
export { PostgresTableSchemaFieldCreateVisitor } from './visitors/PostgresTableSchemaFieldCreateVisitor';
