// DI registration
export { v2RecordRepositoryPostgresTokens, registerV2RecordRepositoryPostgresAdapter } from './di';
export type { IV2RecordRepositoryPostgresConfig } from './di';

// Query builders
export {
  FieldOutputColumnVisitor,
  TableRecordQueryBuilderManager,
  COMPUTED_TABLE_ALIAS,
  ComputedTableRecordQueryBuilder,
  ComputedFieldSelectExpressionVisitor,
  StoredFieldSelectVisitor,
  StoredTableRecordQueryBuilder,
  RecordInsertBuilder,
  RecordUpdateBuilder,
} from './query-builder';
export type {
  IQueryBuilderDeps,
  ITableRecordQueryBuilder,
  QB,
  DynamicDB,
  SystemColumn,
  OrderByColumn,
  FieldOutputColumn,
  QueryMode,
  IQueryBuilderManagerOptions,
  IDirtyFilterConfig,
  IComputedQueryBuilderOptions,
  LinkOrderBy,
  LateralColumnType,
  ILateralContext,
  ComputedFieldSelectExpressionVisitorOptions,
  IStoredQueryBuilderOptions,
  CompiledSqlStatement,
  RecordInsertSqlResult,
  RecordInsertDataResult,
  RecordInsertBuilderContext,
  LinkedRecordLockInfo,
  InsertExclusivityConstraint,
  UserFieldColumn,
  RecordUpdateSqlResult,
  RecordUpdateBuilderContext,
} from './query-builder';

// Computed updates
export {
  defaultFieldBackfillConfig,
  ComputedFieldBackfillService,
  ComputedFieldCascadeAfterSchemaUpdate,
  ComputedUpdateDrainService,
  ComputedFieldUpdater,
  defaultComputedUpdateLockConfig,
  COMPUTED_UPDATE_LOCK_UNAVAILABLE_CODE,
  buildComputedUpdateLockPlan,
  buildAdvisoryLockStatement,
  buildAdvisoryLockQuery,
  buildTryAdvisoryLockQuery,
  isComputedUpdateLockUnavailable,
  allTargetRecordsReasonValues,
  isAllTargetRecordsReason,
  ComputedUpdatePlanner,
  computedFieldTypes,
  isComputedFieldType,
  splitSeedGroupsForPlan,
  createComputedUpdateRun,
  toRunLogContext,
  toRunSpanAttributes,
  ExternalComputedRefreshService,
  RunComputedTaskByIdCommand,
  RunComputedTaskByIdHandler,
  UserRenamePropagationService,
  FieldDependencyGraph,
  UpdateFromSelectBuilder,
  isPersistedAsGeneratedColumn,
  dedupeClaimRowsByScope,
  ComputedUpdateOutbox,
  mergeBeforeImageRecordDtos,
  serializeComputedUpdatePlan,
  computePlanHash,
  buildOutboxTaskInput,
  mergeComputedRealtimeOrchestration,
  deserializeComputedUpdatePlan,
  serializeSeedPayload,
  deserializeSeedPayload,
  computeSeedHash,
  buildSeedTaskInput,
  isSeedPayload,
  mergeSeedPayloads,
  serializeFieldBackfillPayload,
  deserializeFieldBackfillPayload,
  computeFieldBackfillHash,
  buildFieldBackfillTaskInput,
  isFieldBackfillPayload,
  defaultComputedUpdateOutboxConfig,
  normalizeComputedUpdateOutboxConfig,
  isFieldBackfillOutboxItem,
  isSeedOutboxItem,
  ComputedUpdatePauseRegistry,
  buildComputedTaskNotPausedCondition,
  COMPUTED_UPDATE_PAUSE_SCOPE_TABLE,
  computedUpdatePauseScopeTypes,
  AsyncWithRetryStrategy,
  defaultHybridWithOutboxStrategyConfig,
  productionHybridWithOutboxStrategyConfig,
  lowLatencyHybridWithOutboxStrategyConfig,
  HybridWithOutboxStrategy,
  SyncInTransactionStrategy,
  buildBatchUpdateTrigger,
  splitComputedTaskForSeedRecordLimit,
  splitSeedTaskForSeedRecordLimit,
  ComputedUpdateWorker,
  defaultPollingConfig,
  hybridPollingConfig,
  externalPollingConfig,
  ComputedUpdatePollingService,
  startComputedUpdatePollingIfEnabled,
} from './computed';
export type {
  CascadeInput,
  FieldChangeData,
  RecordChangeData,
  StepChangeData,
  ComputedUpdateResult,
  DirtyRecordStats,
  DirtyPropagationStats,
  ExecutePreparedStepsResult,
  PreparedDirtyState,
  ComputedUpdateLockConfig,
  ComputedUpdateLockSummary,
  ComputedUpdateLockRecord,
  ComputedUpdateLockTable,
  ComputedUpdateLockBatch,
  ComputedUpdateLockStatement,
  ComputedUpdateLockPlan,
  UpdateContext,
  ComputedSeedGroup,
  ComputedBeforeImageRecord,
  ComputedBeforeImageRequirements,
  PlanStageContext,
  UpdateImpactHint,
  UpdateStep,
  SameTableBatch,
  DirtyPropagationMode,
  AllTargetRecordsReason,
  ComputedUpdateCyclePolicy,
  ConditionalFilterCondition,
  ComputedDependencyEdge,
  ComputedUpdateCycleInfo,
  ComputedUpdatePlan,
  ComputedUpdateRunPhase,
  ComputedUpdateRunContext,
  IRunComputedTaskByIdCommandInput,
  RunComputedTaskByIdResult,
  FieldDependencyEdge,
  LinkRelationship,
  FieldMeta,
  FieldDependencyGraphData,
  CrossBaseFieldMeta,
  FieldDependencyGraphLoadOptions,
  UpdateRecordFilter,
  DirtyFilterConfig,
  UpdateFromSelectParams,
  UpdateWithReturningResult,
  UpdatedRecordRow,
  OutboxRow,
  ComputedUpdateStepDto,
  ComputedDependencyEdgeDto,
  ComputedUpdateSeedGroupDto,
  ComputedBeforeImageRecordDto,
  ComputedRealtimeOrchestrationDto,
  ComputedUpdateOutboxPayload,
  ComputedUpdateRunMeta,
  ComputedUpdateOutboxTaskInput,
  ComputedUpdateOutboxItem,
  SeedImpactHintDto,
  ComputedUpdateSeedPayload,
  ComputedUpdateSeedTaskInput,
  DeserializedSeedTask,
  OutboxTaskType,
  FieldBackfillOutboxPayload,
  FieldBackfillOutboxTaskInput,
  ComputedUpdateOutboxConfig,
  ClaimBatchParams,
  ClaimByIdParams,
  RenewLeaseParams,
  ReleaseForRetryParams,
  FieldBackfillOutboxItem,
  SeedOutboxItem,
  AnyOutboxItem,
  IComputedUpdateOutbox,
  ComputedUpdatePauseScopeType,
  ComputedUpdatePauseScope,
  PauseComputedUpdateScopeParams,
  ResumeComputedUpdateScopeParams,
  ListComputedUpdatePauseScopesParams,
  IComputedUpdatePauseRegistry,
  UpdateStrategyMode,
  IUpdateStrategy,
  DispatchMode,
  HybridWithOutboxStrategyConfig,
  LinkChangeType,
  LinkRelationshipType,
  LinkChange,
  UpdateTrigger,
  BatchUpdateTrigger,
  ComputedUpdateWorkerParams,
  ComputedUpdateWorkerRunTaskByIdParams,
  ComputedUpdatePollingConfig,
} from './computed';

// Repository
export {
  PostgresTableRecordQueryRepository,
  PostgresTableRecordRepository,
  PostgresRecordMutationSnapshotCaptureService,
  PostgresRecordOrderCalculator,
  PostgresAttachmentLookupService,
  parseThumbnailPath,
  PostgresUserLookupService,
  OffsetStreamPaginationStrategy,
  CursorStreamPaginationStrategy,
} from './repository';
export type {
  RecordMutationSnapshotTraceContext,
  IPostgresRecordMutationSnapshotCaptureSession,
  IPostgresRecordMutationSnapshotCaptureService,
} from './repository';

// Visitors
export {
  FieldDatabaseValueVisitor,
  FieldSqlLiteralVisitor,
  FieldInsertValueVisitor,
  LinkChangeCollectorVisitor,
  createEmptyCollectedLinkChanges,
  mergeCollectedLinkChange,
  LinkExclusivityConstraintCollector,
  TableRecordConditionWhereVisitor,
  CellValueMutateVisitor,
  FieldDeleteValueVisitor,
} from './visitors';
export type {
  FieldInsertResult,
  QueryExecutor,
  LinkChangeCollectorContext,
  LinkChangeCollectorResult,
  CollectedLinkChanges,
  LinkExclusivityConstraint,
  LinkExclusivityCollectorContext,
  LinkExclusivityCollectorResult,
  RecordConditionWhere,
  TableRecordConditionWhereVisitorOptions,
  MutationStatements,
  CellValueMutateContext,
  FieldDeleteResult,
  OutgoingLinkDeleteOp,
} from './visitors';
